permalink: /:categories/:title.html
url: "https://experimentalinsanity.github.io/jekyll-masonry/"
full_name: "JD DeFauw"
first_name: "JD"
last_name: "DeFauw"
blog_title: "Blog title "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "opi-tech"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: ""
github: ""
facebook: ""
linkined_url: ""
